# `jc` error with large output to parsed

```
root@DataCenterCompute001:~# lsusb --verbose | jc -p --lsusb -d
Traceback (most recent call last):
  File "/usr/bin/jc", line 33, in <module>
    sys.exit(load_entry_point('jc==1.17.3', 'console_scripts', 'jc')())
  File "/usr/lib/python3/dist-packages/jc/cli.py", line 643, in main
    result = parser.parse(data, raw=raw, quiet=quiet)
  File "/usr/lib/python3/dist-packages/jc/parsers/lsusb.py", line 834, in parse
    if lsusb._populate_lists(line):
  File "/usr/lib/python3/dist-packages/jc/parsers/lsusb.py", line 520, in _populate_lists
    self.hub_port_status_list.append(self._add_hub_port_status_attributes(line))
  File "/usr/lib/python3/dist-packages/jc/parsers/lsusb.py", line 394, in _add_hub_port_status_attributes
    second_split = first_split[1].split(maxsplit=1)
IndexError: list index out of range
root@DataCenterCompute001:~#
```
